openapi: 3.0.3
info:
  title: 订单API (FastAdmin)
  description: 基于FastAdmin + ThinkPHP的订单管理API接口
  version: 1.0.0
  contact:
    name: API支持团队
    email: support@example.com

servers:
  - url: https://api.example.com
    description: 生产环境
  - url: http://localhost:8080
    description: 开发环境

tags:
  - name: order
    description: 订单相关接口

paths:
  /api/order/lists:
    get:
      tags:
        - order
      summary: 获取订单列表
      description: 分页查询当前用户的订单列表,支持按状态筛选
      operationId: getOrderList
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token(也可通过query传递)
          required: true
          schema:
            type: string
            example: "abcdef1234567890"
        - name: filter
          in: query
          description: 筛选条件(JSON格式),如{"status":"paid"}
          required: false
          schema:
            type: string
            example: '{"status":"paid"}'
        - name: page
          in: query
          description: 页码(从1开始)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: 每页数量(FastAdmin使用limit而非pageSize)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: 排序字段(默认id)
          required: false
          schema:
            type: string
            default: "id"
            example: "createtime"
        - name: order
          in: query
          description: 排序方式(asc/desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: "desc"
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  total: 15
                  per_page: 20
                  current_page: 1
                  last_page: 1
                  data:
                    - id: 456
                      order_no: "ORD20250112153045A3B7F2"
                      original_amount: 150.00
                      discount_amount: 50.00
                      final_amount: 100.00
                      status: "paid"
                      store_name: "测试门店A"
                      createtime: 1736697510
                      verified_at: null
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/order/detail:
    get:
      tags:
        - order
      summary: 获取订单详情
      description: 查询指定订单的详细信息,包括门店信息、核销券信息、核销记录等
      operationId: getOrderDetail
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: 订单ID
          required: true
          schema:
            type: integer
            example: 456
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  id: 456
                  order_no: "ORD20250112153045A3B7F2"
                  original_amount: 150.00
                  discount_amount: 50.00
                  final_amount: 100.00
                  status: "paid"
                  store_name: "测试门店A"
                  store_address: "北京市朝阳区测试路1号"
                  store_phone: "010-12345678"
                  voucher_title: "50元代金券"
                  voucher_type: "cash"
                  createtime: 1736697510
                  verified_at: null
                  verified_by: null
                  remark: "客户要求微辣"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: token
      description: FastAdmin Token认证,可通过Header或Query传递

  schemas:
    OrderStatus:
      type: string
      enum:
        - pending
        - paid
        - verified
        - cancelled
        - refunded
      description: |
        订单状态:
        - pending: 待支付
        - paid: 已支付
        - verified: 已核销
        - cancelled: 已取消
        - refunded: 已退款

    OrderListItem:
      type: object
      required:
        - id
        - orderNo
        - originalAmount
        - discountAmount
        - finalAmount
        - status
        - storeName
        - createdAt
      properties:
        id:
          type: integer
          description: 订单ID
          example: 456
        orderNo:
          type: string
          description: 订单号
          pattern: '^ORD\d{14}[A-Z0-9]{6}$'
          example: "ORD20250112153045A3B7F2"
        originalAmount:
          type: number
          format: double
          description: 原价
          minimum: 0
          maximum: 99999.99
          example: 150.00
        discountAmount:
          type: number
          format: double
          description: 优惠金额
          minimum: 0
          maximum: 99999.99
          example: 50.00
        finalAmount:
          type: number
          format: double
          description: 实付金额
          minimum: 0
          maximum: 99999.99
          example: 100.00
        status:
          $ref: '#/components/schemas/OrderStatus'
        storeName:
          type: string
          description: 门店名称
          maxLength: 100
          example: "测试门店A"
        createdAt:
          type: integer
          format: int64
          description: 创建时间(Unix时间戳)
          example: 1736697510
        verifiedAt:
          type: integer
          format: int64
          description: 核销时间(Unix时间戳,已核销时显示)
          example: 1736697645

    OrderDetail:
      allOf:
        - $ref: '#/components/schemas/OrderListItem'
        - type: object
          properties:
            storeAddress:
              type: string
              description: 门店地址
              maxLength: 200
              example: "北京市朝阳区测试路1号"
            storePhone:
              type: string
              description: 门店电话
              pattern: '^\d{3,4}-?\d{7,8}$'
              example: "010-12345678"
            voucherTitle:
              type: string
              description: 核销券标题(使用券时显示)
              maxLength: 100
              example: "50元代金券"
            voucherType:
              type: string
              description: 核销券类型(使用券时显示)
              enum:
                - cash
                - discount
                - exchange
                - trial
              example: "cash"
            verifiedBy:
              type: string
              description: 核销员工(已核销时显示)
              maxLength: 100
              example: "店员001"
            remark:
              type: string
              description: 备注
              example: "客户要求微辣"

    FastAdminSuccessResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: 状态码(1=成功)
          example: 1
        msg:
          type: string
          description: 响应消息
          example: "操作成功"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600
        data:
          type: object
          description: 响应数据(可选)

    FastAdminErrorResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: |
            错误码:
            - 0: 失败
            - -1: 参数错误
            - -2: 未授权
            - -3: 无权限
            - -4: 资源不存在
          example: 0
        msg:
          type: string
          description: 错误消息
          example: "操作失败"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600

  responses:
    Unauthorized:
      description: 未授权,Token无效或已过期
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -2
            msg: "Token无效或已过期"
            time: 1736697600

    NotFound:
      description: 请求的资源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -4
            msg: "订单不存在或已被删除"
            time: 1736697600

    InternalServerError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: 0
            msg: "服务器内部错误,请稍后重试"
            time: 1736697600

