openapi: 3.0.3
info:
  title: 门店API (FastAdmin)
  description: 基于FastAdmin + ThinkPHP的门店管理API接口
  version: 1.0.0
  contact:
    name: API支持团队
    email: support@example.com

servers:
  - url: https://api.example.com
    description: 生产环境
  - url: http://localhost:8080
    description: 开发环境

tags:
  - name: store
    description: 门店相关接口

paths:
  /api/store/detail:
    get:
      tags:
        - store
      summary: 获取门店详情
      description: 查询指定门店的详细信息,包括地址、电话、营业时间、地理位置等
      operationId: getStoreDetail
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: 门店ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  id: 1
                  name: "测试门店A"
                  address: "北京市朝阳区测试路1号"
                  phone: "010-12345678"
                  longitude: 116.407526
                  latitude: 39.904030
                  business_hours: "09:00-21:00"
                  is_active: 1
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/store/lists:
    get:
      tags:
        - store
      summary: 获取门店列表
      description: 查询门店列表,支持按营业状态筛选、地理位置排序
      operationId: getStoreList
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token(也可通过query传递)
          required: true
          schema:
            type: string
            example: "abcdef1234567890"
        - name: filter
          in: query
          description: 筛选条件(JSON格式),如{"is_active":1}
          required: false
          schema:
            type: string
            example: '{"is_active":1}'
        - name: longitude
          in: query
          description: 当前位置经度(用于距离排序)
          required: false
          schema:
            type: number
            format: double
            minimum: -180
            maximum: 180
            example: 116.407526
        - name: latitude
          in: query
          description: 当前位置纬度(用于距离排序)
          required: false
          schema:
            type: number
            format: double
            minimum: -90
            maximum: 90
            example: 39.904030
        - name: page
          in: query
          description: 页码(从1开始)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: 每页数量(FastAdmin使用limit而非pageSize)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: 排序字段(默认id)
          required: false
          schema:
            type: string
            default: "id"
        - name: order
          in: query
          description: 排序方式(asc/desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: "asc"
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  total: 2
                  per_page: 20
                  current_page: 1
                  last_page: 1
                  data:
                    - id: 1
                      name: "测试门店A"
                      address: "北京市朝阳区测试路1号"
                      phone: "010-12345678"
                      longitude: 116.407526
                      latitude: 39.904030
                      business_hours: "09:00-21:00"
                      is_active: 1
                      distance: 1.2
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: token
      description: FastAdmin Token认证,可通过Header或Query传递

  schemas:
    StoreDetail:
      type: object
      required:
        - id
        - name
        - address
        - phone
        - longitude
        - latitude
        - businessHours
        - isActive
      properties:
        id:
          type: integer
          description: 门店ID
          example: 1
        name:
          type: string
          description: 门店名称
          maxLength: 100
          example: "测试门店A"
        address:
          type: string
          description: 门店地址
          maxLength: 200
          example: "北京市朝阳区测试路1号"
        phone:
          type: string
          description: 联系电话
          pattern: '^\d{3,4}-?\d{7,8}$'
          example: "010-12345678"
        longitude:
          type: number
          format: double
          description: 经度
          minimum: -180
          maximum: 180
          example: 116.407526
        latitude:
          type: number
          format: double
          description: 纬度
          minimum: -90
          maximum: 90
          example: 39.904030
        businessHours:
          type: string
          description: 营业时间
          pattern: '^\d{2}:\d{2}-\d{2}:\d{2}$'
          example: "09:00-21:00"
        isActive:
          type: integer
          description: 是否营业中(1=营业,0=关闭)
          enum: [0, 1]
          example: 1

    StoreListItem:
      allOf:
        - $ref: '#/components/schemas/StoreDetail'
        - type: object
          properties:
            distance:
              type: number
              format: double
              description: 距离当前位置的距离(公里),仅当提供了经纬度参数时返回
              minimum: 0
              example: 1.2

    FastAdminSuccessResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: 状态码(1=成功)
          example: 1
        msg:
          type: string
          description: 响应消息
          example: "操作成功"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600
        data:
          type: object
          description: 响应数据(可选)

    FastAdminErrorResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: |
            错误码:
            - 0: 失败
            - -1: 参数错误
            - -2: 未授权
            - -3: 无权限
            - -4: 资源不存在
          example: 0
        msg:
          type: string
          description: 错误消息
          example: "操作失败"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600

  responses:
    Unauthorized:
      description: 未授权,Token无效或已过期
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -2
            msg: "Token无效或已过期"
            time: 1736697600

    NotFound:
      description: 请求的资源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -4
            msg: "门店不存在或已被删除"
            time: 1736697600

    InternalServerError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: 0
            msg: "服务器内部错误,请稍后重试"
            time: 1736697600

