openapi: 3.0.3
info:
  title: 核销券API (FastAdmin)
  description: 基于FastAdmin + ThinkPHP的核销券管理API接口
  version: 1.0.0
  contact:
    name: API支持团队
    email: support@example.com

servers:
  - url: https://api.example.com
    description: 生产环境
  - url: http://localhost:8080
    description: 开发环境

tags:
  - name: voucher
    description: 核销券相关接口

paths:
  /api/voucher/lists:
    get:
      tags:
        - voucher
      summary: 获取核销券列表
      description: 分页查询当前用户的核销券列表,支持按状态和类型筛选
      operationId: getVoucherList
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token(也可通过query传递)
          required: true
          schema:
            type: string
            example: "abcdef1234567890"
        - name: filter
          in: query
          description: 筛选条件(JSON格式),如{"status":"unused","type":"cash"}
          required: false
          schema:
            type: string
            example: '{"status":"unused"}'
        - name: page
          in: query
          description: 页码(从1开始)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: 每页数量(FastAdmin使用limit而非pageSize)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: 排序字段(默认id)
          required: false
          schema:
            type: string
            default: "id"
            example: "createtime"
        - name: order
          in: query
          description: 排序方式(asc/desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: "desc"
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  total: 25
                  per_page: 20
                  current_page: 1
                  last_page: 2
                  data:
                    - id: 123
                      code: "VCH20250112001"
                      type: "cash"
                      title: "50元代金券"
                      description: "全场通用,满100可用"
                      amount: 50.00
                      discount: null
                      status: "unused"
                      expire_at: 1735660799
                      store_name: "测试门店A"
                      store_address: "北京市朝阳区测试路1号"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/voucher/detail:
    get:
      tags:
        - voucher
      summary: 获取核销券详情
      description: 查询指定核销券的详细信息,包括门店信息、使用记录等
      operationId: getVoucherDetail
      security:
        - tokenAuth: []
      parameters:
        - name: token
          in: header
          description: 用户Token
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: 核销券ID
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastAdminSuccessResponse'
              example:
                code: 1
                msg: "查询成功"
                time: 1736697600
                data:
                  id: 123
                  code: "VCH20250112001"
                  type: "cash"
                  title: "50元代金券"
                  description: "全场通用,满100可用"
                  amount: 50.00
                  status: "unused"
                  expire_at: 1735660799
                  used_at: null
                  order_id: null
                  order_no: null
                  store_id: 1
                  store_name: "测试门店A"
                  store_address: "北京市朝阳区测试路1号"
                  store_phone: "010-12345678"
                  business_hours: "09:00-21:00"
                  longitude: 116.407526
                  latitude: 39.904030
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: token
      description: FastAdmin Token认证,可通过Header或Query传递

  schemas:
    VoucherType:
      type: string
      enum:
        - cash
        - discount
        - exchange
        - trial
      description: |
        核销券类型:
        - cash: 代金券
        - discount: 折扣券
        - exchange: 兑换券
        - trial: 体验券

    VoucherStatus:
      type: string
      enum:
        - unused
        - used
        - expired
        - frozen
      description: |
        核销券状态:
        - unused: 未使用
        - used: 已使用
        - expired: 已过期
        - frozen: 已冻结

    VoucherListItem:
      type: object
      required:
        - id
        - code
        - type
        - title
        - description
        - status
        - expireAt
        - storeName
        - storeAddress
      properties:
        id:
          type: integer
          description: 核销券ID
          example: 123
        code:
          type: string
          description: 核销码
          example: "VCH20250112001"
        type:
          $ref: '#/components/schemas/VoucherType'
        title:
          type: string
          description: 券标题
          maxLength: 100
          example: "50元代金券"
        description:
          type: string
          description: 券描述
          example: "全场通用,满100可用"
        amount:
          type: number
          format: double
          description: 金额(代金券专用)
          minimum: 0.01
          maximum: 99999.99
          example: 50.00
        discount:
          type: number
          format: double
          description: 折扣(折扣券专用,0.1-0.99)
          minimum: 0.1
          maximum: 0.99
          example: 0.8
        status:
          $ref: '#/components/schemas/VoucherStatus'
        expireAt:
          type: integer
          format: int64
          description: 过期时间(Unix时间戳)
          example: 1735660799
        storeName:
          type: string
          description: 门店名称
          example: "测试门店A"
        storeAddress:
          type: string
          description: 门店地址
          example: "北京市朝阳区测试路1号"

    VoucherDetail:
      allOf:
        - $ref: '#/components/schemas/VoucherListItem'
        - type: object
          properties:
            usedAt:
              type: integer
              format: int64
              description: 使用时间(Unix时间戳,已使用时显示)
              example: 1736697045
            orderId:
              type: integer
              description: 关联订单ID(已使用时显示)
              example: 456
            orderNo:
              type: string
              description: 关联订单号(已使用时显示)
              example: "ORD20250112153045A3B7F2"
            storePhone:
              type: string
              description: 门店电话
              pattern: '^\d{3,4}-?\d{7,8}$'
              example: "010-12345678"
            businessHours:
              type: string
              description: 营业时间
              pattern: '^\d{2}:\d{2}-\d{2}:\d{2}$'
              example: "09:00-21:00"
            longitude:
              type: number
              format: double
              description: 门店经度
              minimum: -180
              maximum: 180
              example: 116.407526
            latitude:
              type: number
              format: double
              description: 门店纬度
              minimum: -90
              maximum: 90
              example: 39.904030

    FastAdminSuccessResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: 状态码(1=成功)
          example: 1
        msg:
          type: string
          description: 响应消息
          example: "操作成功"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600
        data:
          type: object
          description: 响应数据(可选)

    FastAdminErrorResponse:
      type: object
      required:
        - code
        - msg
        - time
      properties:
        code:
          type: integer
          description: |
            错误码:
            - 0: 失败
            - -1: 参数错误
            - -2: 未授权
            - -3: 无权限
            - -4: 资源不存在
          example: 0
        msg:
          type: string
          description: 错误消息
          example: "操作失败"
        time:
          type: integer
          format: int64
          description: 响应时间戳(秒)
          example: 1736697600

  responses:
    Unauthorized:
      description: 未授权,Token无效或已过期
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -2
            msg: "Token无效或已过期"
            time: 1736697600

    NotFound:
      description: 请求的资源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: -4
            msg: "核销券不存在或已被删除"
            time: 1736697600

    InternalServerError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FastAdminErrorResponse'
          example:
            code: 0
            msg: "服务器内部错误,请稍后重试"
            time: 1736697600

