openapi: 3.0.3
info:
  title: 商家API
  description: 粮仓Mix - 商家列表与商家详情API规范
  version: 1.0.0
  contact:
    name: 粮仓Mix开发团队

servers:
  - url: https://api.example.com
    description: 生产环境
  - url: https://dev-api.example.com
    description: 开发环境

tags:
  - name: merchant
    description: 商家相关接口

paths:
  /api/merchant/list:
    get:
      tags:
        - merchant
      summary: 获取商家列表
      description: 根据用户所在区域获取商家列表,支持分页
      operationId: getMerchantList
      parameters:
        - name: province
          in: query
          description: 省份名称(如"黑龙江省")
          required: false
          schema:
            type: string
            example: "黑龙江省"
        - name: city
          in: query
          description: 城市名称(如"哈尔滨市"),优先使用city过滤
          required: false
          schema:
            type: string
            example: "哈尔滨市"
        - name: page
          in: query
          description: 页码,从1开始
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: limit
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
            example: 20
        - name: filter
          in: query
          description: 筛选条件(JSON字符串),如{"is_active":1}
          required: false
          schema:
            type: string
            example: '{"is_active":1}'
      responses:
        '200':
          description: 成功获取商家列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantListResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/merchant/detail:
    get:
      tags:
        - merchant
      summary: 获取商家详情
      description: 根据商家ID获取商家详细信息
      operationId: getMerchantDetail
      parameters:
        - name: id
          in: query
          description: 商家ID
          required: true
          schema:
            type: integer
            example: 1001
      responses:
        '200':
          description: 成功获取商家详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantDetailResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 商家不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/merchant/{id}/products:
    get:
      tags:
        - merchant
      summary: 获取商家供应的产品
      description: 获取指定商家已上架的平台产品分类,包含当前区域价格
      operationId: getMerchantProducts
      parameters:
        - name: id
          in: path
          description: 商家ID
          required: true
          schema:
            type: integer
            example: 1001
        - name: province
          in: query
          description: 省份名称,用于获取区域价格
          required: false
          schema:
            type: string
            example: "黑龙江省"
        - name: city
          in: query
          description: 城市名称,用于获取区域价格
          required: false
          schema:
            type: string
            example: "哈尔滨市"
      responses:
        '200':
          description: 成功获取商家产品列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantProductsResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 商家不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Merchant:
      type: object
      description: 商家实体
      required:
        - id
        - name
        - region_id
        - region_name
        - province
        - city
        - is_active
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: 商家ID
          example: 1001
        name:
          type: string
          description: 商家名称
          minLength: 2
          maxLength: 50
          example: "五常大米批发店"
        logo:
          type: string
          nullable: true
          description: 商家Logo图片URL
          example: "https://cdn.example.com/logos/merchant_1001.jpg"
        region_id:
          type: integer
          description: 所属区域ID
          example: 230100
        region_name:
          type: string
          description: 所属区域名称
          example: "哈尔滨市"
        province:
          type: string
          description: 所属省份
          example: "黑龙江省"
        city:
          type: string
          description: 所属城市
          example: "哈尔滨市"
        address:
          type: string
          nullable: true
          description: 详细地址
          example: "南岗区中央大街123号"
        phone:
          type: string
          nullable: true
          description: 联系电话
          pattern: '^1[3-9]\d{9}$'
          example: "13800138000"
        business_hours:
          type: string
          nullable: true
          description: 营业时间
          example: "09:00-18:00"
        description:
          type: string
          nullable: true
          description: 商家简介
          example: "专营五常大米,品质保证"
        is_active:
          type: integer
          description: 是否营业(1=营业,0=关闭)
          enum: [0, 1]
          example: 1
        rating:
          type: number
          nullable: true
          description: 用户评分(0-5)
          minimum: 0
          maximum: 5
          example: 4.5
        years_in_business:
          type: integer
          nullable: true
          description: 经营年限
          example: 5
        certification_status:
          type: string
          nullable: true
          description: 认证状态
          enum: [verified, pending, none]
          example: "verified"
        created_at:
          type: string
          format: date-time
          description: 创建时间
          example: "2024-01-01T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: 更新时间
          example: "2024-10-14T12:00:00Z"

    MerchantListItem:
      allOf:
        - $ref: '#/components/schemas/Merchant'
        - type: object
          properties:
            distance:
              type: number
              nullable: true
              description: 距离用户的距离(公里),仅当用户提供位置时返回
              example: 2.5
            product_tags:
              type: array
              nullable: true
              description: 该商家支持的产品分类标签
              items:
                type: string
              example: ["大米", "碎米"]

    MerchantProduct:
      type: object
      description: 商家供应的产品(包含产品分类信息和区域价格)
      required:
        - category_id
        - category_name
        - category_image
        - price
        - price_unit
        - is_available
      properties:
        category_id:
          type: integer
          description: 产品分类ID
          example: 1
        category_name:
          type: string
          description: 产品分类名称
          example: "大米"
        category_image:
          type: string
          description: 产品分类图片URL
          example: "https://cdn.example.com/categories/rice.jpg"
        description:
          type: string
          nullable: true
          description: 产品分类描述
          example: "优质东北大米"
        price:
          type: number
          description: 当前区域价格(元)
          example: 5.00
        price_unit:
          type: string
          description: 价格单位
          example: "元/斤"
        is_available:
          type: boolean
          description: 是否有货
          example: true
        stock_status:
          type: string
          nullable: true
          description: 库存状态描述
          example: "充足"

    PaginationMeta:
      type: object
      description: 分页元信息
      required:
        - total
        - per_page
        - current_page
        - last_page
      properties:
        total:
          type: integer
          description: 总记录数
          example: 150
        per_page:
          type: integer
          description: 每页数量
          example: 20
        current_page:
          type: integer
          description: 当前页码
          example: 1
        last_page:
          type: integer
          description: 总页数
          example: 8

    MerchantListResponse:
      type: object
      description: 商家列表响应(FastAdmin分页格式)
      required:
        - code
        - msg
        - data
      properties:
        code:
          type: integer
          description: 响应码(0=成功,非0=失败)
          example: 0
        msg:
          type: string
          description: 响应消息
          example: "success"
        data:
          type: object
          required:
            - total
            - per_page
            - current_page
            - last_page
            - data
          properties:
            total:
              type: integer
              description: 总记录数
              example: 150
            per_page:
              type: integer
              description: 每页数量
              example: 20
            current_page:
              type: integer
              description: 当前页码
              example: 1
            last_page:
              type: integer
              description: 总页数
              example: 8
            data:
              type: array
              description: 商家列表
              items:
                $ref: '#/components/schemas/MerchantListItem'

    MerchantDetailResponse:
      type: object
      description: 商家详情响应
      required:
        - code
        - msg
        - data
      properties:
        code:
          type: integer
          description: 响应码(0=成功,非0=失败)
          example: 0
        msg:
          type: string
          description: 响应消息
          example: "success"
        data:
          $ref: '#/components/schemas/Merchant'

    MerchantProductsResponse:
      type: object
      description: 商家产品列表响应
      required:
        - code
        - msg
        - data
      properties:
        code:
          type: integer
          description: 响应码(0=成功,非0=失败)
          example: 0
        msg:
          type: string
          description: 响应消息
          example: "success"
        data:
          type: object
          required:
            - products
          properties:
            products:
              type: array
              description: 商家供应的产品列表
              items:
                $ref: '#/components/schemas/MerchantProduct'

    ErrorResponse:
      type: object
      description: 错误响应
      required:
        - code
        - msg
      properties:
        code:
          type: integer
          description: 错误码(非0)
          example: 400
        msg:
          type: string
          description: 错误消息
          example: "参数错误:缺少必填参数id"
        data:
          type: object
          nullable: true
          description: 错误详情(可选)
